# Provisions the cloudskew infrastructure in the production environment.

pool:
  vmImage: ubuntu-latest

trigger: none

name: cloudskew-setup.production

variables:
  - group: cloudskew-variable-group

stages:
  - template: templates/setup.yml
    parameters:
      azureSubscription: $(provisioning-service-connection)
      environment: production
